name: artifact

on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened]
    branches: [master]
  
jobs:
  artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get Info 
        run: | 
          echo "::set-output name=version::$(awk '/##/{gsub(/[^0-9]+.[^0-9]+.[^0-9]/, "", $NF); print $NF}' CHANGELOG.md | awk 'NR==1{print $1}')"
        id: info
      - name: Build Artifact
        run: |
          cd ${{ github.workspace }}
          chmod +x ./pack.sh
          ./pack.sh
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: onlyoffice
          path: onlyoffice