name: Lint

on:
  workflow_dispatch:
  pull_request:
    branches: [master]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: cs2pr, phpcs
          
      - name: Run phpcs
        run: phpcs -q --extensions=php,module,inc,install,test,profile,theme,css,info --ignore=node_modules,bower_components,vendor,md,yml,txt ./